import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from datetime import datetime
from dotenv import load_dotenv

from src.config import load_api_keys, TEMPERATURE_QUESTION, MAX_TURNS, MIN_TURNS
from src.llm_client import GeminiClient
from src.state import CandidateProfile
from src.agents import InterviewerAgent, EvaluatorAgent, AdaptiveControllerAgent, CoachAgent
from src.orchestrator import InterviewOrchestrator


PERSONAS = {
    "strong": (
        "You are a strong interview candidate. You give specific, metric-driven answers "
        "with concrete examples from real projects. You structure your answers clearly, "
        "often using the STAR framework. You cite specific numbers, outcomes, and lessons learned. "
        "You show depth of reasoning and connect your experience to the role. "
        "Keep answers to 3-5 sentences — concise but rich in detail."
    ),
    "weak": (
        "You are a weak interview candidate. You give vague, generic answers without "
        "specific examples. You say things like 'I would collaborate with stakeholders' "
        "and 'I'm a team player' without any concrete evidence. You never cite numbers "
        "or measurable outcomes. Your answers are surface-level and could apply to any role. "
        "Keep answers to 2-3 sentences."
    ),
    "evasive": (
        "You are an evasive interview candidate. Follow this exact pattern:\n"
        "- For the FIRST question: give a completely off-topic answer about something unrelated "
        "(talk about your hobby or a random topic instead of answering the question).\n"
        "- For the SECOND question: say 'Honestly, I don't know much about that area.'\n"
        "- For the THIRD question: give another off-topic answer, redirecting to something irrelevant.\n"
        "- For the FOURTH question onward: give thin, minimal answers that technically address "
        "the question but with no depth or examples. 1-2 sentences max.\n"
        "Keep answers short throughout."
    ),
}


def simulate(client: GeminiClient, persona_prompt: str, question: str, prior_answers: list[str]) -> str:
    context = ""
    if prior_answers:
        context = "Your previous answers in this interview:\n"
        for i, a in enumerate(prior_answers, 1):
            context += f"  Answer {i}: {a}\n"
        context += "\n"

    user_content = f"{context}Interview question: {question}\n\nGive your answer as this candidate persona."

    return client.generate(persona_prompt, user_content, TEMPERATURE_QUESTION)


def run_simulation(persona: str, role: str, focus: str, out_path: str):
    load_dotenv()
    keys = load_api_keys()
    client = GeminiClient(keys)

    persona_prompt = PERSONAS[persona]
    profile = CandidateProfile(target_role=role, focus_area=focus)

    interviewer = InterviewerAgent(client)
    evaluator = EvaluatorAgent(client)
    controller = AdaptiveControllerAgent(client)
    coach = CoachAgent(client)

    orchestrator = InterviewOrchestrator(interviewer, evaluator, controller, coach)

    gen = orchestrator.run(profile)
    prior_answers: list[str] = []
    state = None
    report = None

    event = next(gen)
    while True:
        event_type, turn_num, data = event

        if event_type == "question":
            print(f"  Turn {turn_num}: generating answer...", flush=True)
            answer = simulate(client, persona_prompt, data, prior_answers)
            prior_answers.append(answer)
            event = gen.send(answer)

        elif event_type == "turn_complete":
            turn = data
            print(f"    eval: {turn.evaluation.answer_type} (overall={turn.evaluation.overall}), "
                  f"controller: {turn.decision.action}")
            event = next(gen)

        elif event_type == "report":
            report = data
            event = next(gen)

        elif event_type == "state":
            state = data
            break

    lines = [
        f"# Mock Interview Transcript — {role} ({persona} candidate)",
        f"*Simulated candidate using the `{persona}` persona. "
        f"Answers generated by LLM, not a human.*",
        f"*Focus: {focus} | Generated: {datetime.now().isoformat()}*\n",
    ]

    for t in state.turns:
        lines.append(f"## Turn {t.index} (Difficulty {t.difficulty}/5)")
        lines.append(f"**Question:** {t.question}\n")
        lines.append(f"**Answer:** {t.answer}\n")
        if t.evaluation:
            lines.append("**Evaluation:**")
            lines.append(f"```json\n{json.dumps(t.evaluation.to_dict(), indent=2)}\n```\n")
        if t.decision:
            lines.append(f"**Controller:** action=`{t.decision.action}` | "
                          f"rationale: {t.decision.rationale}\n")
        lines.append("---\n")

    lines.append("## Coach Feedback\n")
    lines.append(report)

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\nTranscript written to {out_path}")


def main():
    parser = argparse.ArgumentParser(description="Simulate a candidate for transcript generation")
    parser.add_argument("--persona", required=True, choices=["strong", "weak", "evasive"])
    parser.add_argument("--role", required=True)
    parser.add_argument("--focus", default="mixed", choices=["behavioral", "technical", "case", "mixed"])
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    print(f"Running {args.persona} simulation for {args.role} ({args.focus})...")
    run_simulation(args.persona, args.role, args.focus, args.out)


if __name__ == "__main__":
    main()
